name: Sleep

on:
  schedule:
    - cron: '5-59/10 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Disable worker
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: curl 'https://api.heroku.com/apps/buckthebot/formation/worker' -X PATCH -H "Authorization: Bearer $HEROKU_API_KEY" -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/vnd.heroku+json; version=3' --data-binary '{"quantity":0,"size":"Free","type":"worker"}'